/* Pilotage personnel pour Grist — dérivé du widget Apache-2.0 de Said Hamadou. */
'use strict';

var TABLES={projects:'PM_SoloProjects',tasks:'PM_SoloTasks',time:'PM_SoloTimeEntries'};
var state={projects:[],tasks:[],time:[],view:'dashboard',project:'',year:new Date().getFullYear(),showDone:false,calendar:new Date(new Date().getFullYear(),new Date().getMonth(),1),demo:false,tick:null,importing:false};
var TASK_STATUSES=[['backlog','À organiser'],['todo','À faire'],['progress','En cours'],['waiting','En attente'],['done','Terminé'],['cancelled','Annulé']];
var PROJECT_STATUSES={planned:'À préparer',active:'En cours',waiting:'En attente',done:'Finalisé',cancelled:'Annulé'};
var MONTHS=['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'];

function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function unix(d){if(!d)return null;var x=new Date(d+'T12:00:00');return Math.floor(x.getTime()/1000)}
function localDateKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dateValue(v){if(!v)return '';var d=new Date(Number(v)*1000);return isNaN(d)?'':localDateKey(d)}
function day(v){if(!v)return null;var d=new Date(Number(v)*1000);return isNaN(d)?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function fmtDate(v){var d=day(v);return d?d.toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function now(){return Math.floor(Date.now()/1000)}
function statusLabel(v){var x=TASK_STATUSES.find(function(s){return s[0]===v});return x?x[1]:v}
function priorityLabel(v){return v==='high'?'Haute':v==='low'?'Basse':'Moyenne'}
function badge(v,type){var cls=v==='high'||v==='cancelled'?'red':v==='progress'||v==='active'?'blue':v==='done'?'green':v==='waiting'||v==='todo'?'amber':'violet';return '<span class="badge '+cls+'">'+esc(type==='priority'?priorityLabel(v):(PROJECT_STATUSES[v]||statusLabel(v)))+'</span>'}
function projectName(id){var p=state.projects.find(function(x){return String(x.id)===String(id)});return p?p.Name:'Sans projet'}
function isDone(s){return s==='done'||s==='cancelled'}
function duration(sec){sec=Math.max(0,Number(sec)||0);var h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?h+' h '+(m?m+' min':''):m+' min'}
function toast(msg){var e=$('toast');e.textContent=msg;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(function(){e.classList.add('hidden')},3000)}

function records(data,map){if(!data||!data.id)return[];return data.id.map(function(id,i){var o={id:id};Object.keys(map).forEach(function(k){o[k]=data[map[k]]?data[map[k]][i]:null});return o})}
function projectMap(){return {Name:'Name',Type:'Type',Status:'Status',Priority:'Priority',Start_Date:'Start_Date',Due_Date:'Due_Date',Progress:'Progress',Next_Action:'Next_Action',Risks:'Risks',Decision:'Decision',Review:'Review',Source_Table:'Source_Table',Source_Record_Id:'Source_Record_Id',Created_At:'Created_At',Updated_At:'Updated_At'}}
function taskMap(){return {Title:'Title',Project_Id:'Project_Id',Type:'Type',Status:'Status',Priority:'Priority',Start_Date:'Start_Date',Due_Date:'Due_Date',Completed_At:'Completed_At',Notes:'Notes',Estimated_Hours:'Estimated_Hours',Review:'Review',Created_At:'Created_At',Updated_At:'Updated_At'}}
function timeMap(){return {Task_Id:'Task_Id',Start_Time:'Start_Time',End_Time:'End_Time',Duration:'Duration',Description:'Description',Source:'Source',Created_At:'Created_At'}}

async function ensureTable(name,columns){try{await grist.docApi.fetchTable(name)}catch(e){await grist.docApi.applyUserActions([['AddTable',name,columns]])}}
async function ensureTables(){
  await ensureTable(TABLES.projects,[{id:'Name',type:'Text'},{id:'Type',type:'Text'},{id:'Status',type:'Choice'},{id:'Priority',type:'Choice'},{id:'Start_Date',type:'Date'},{id:'Due_Date',type:'Date'},{id:'Progress',type:'Int'},{id:'Next_Action',type:'Text'},{id:'Risks',type:'Text'},{id:'Decision',type:'Text'},{id:'Review',type:'Bool'},{id:'Source_Table',type:'Text'},{id:'Source_Record_Id',type:'Int'},{id:'Created_At',type:'DateTime'},{id:'Updated_At',type:'DateTime'}]);
  await ensureTable(TABLES.tasks,[{id:'Title',type:'Text'},{id:'Project_Id',type:'Int'},{id:'Type',type:'Choice'},{id:'Status',type:'Choice'},{id:'Priority',type:'Choice'},{id:'Start_Date',type:'Date'},{id:'Due_Date',type:'Date'},{id:'Completed_At',type:'DateTime'},{id:'Notes',type:'Text'},{id:'Estimated_Hours',type:'Numeric'},{id:'Review',type:'Bool'},{id:'Created_At',type:'DateTime'},{id:'Updated_At',type:'DateTime'}]);
  await ensureTable(TABLES.time,[{id:'Task_Id',type:'Int'},{id:'Start_Time',type:'DateTime'},{id:'End_Time',type:'DateTime'},{id:'Duration',type:'Int'},{id:'Description',type:'Text'},{id:'Source',type:'Choice'},{id:'Created_At',type:'DateTime'}]);
}

function demoLoad(){var raw=localStorage.getItem('pm-solo-demo');if(raw){var d=JSON.parse(raw);state.projects=d.projects||[];state.tasks=d.tasks||[];state.time=d.time||[];return}var y=new Date().getFullYear(),ts=function(m,d){return Math.floor(new Date(y,m,d,12).getTime()/1000)};state.projects=[{id:1,Name:'AMVE — Ambition Mulhouse',Type:'Projet structurant',Status:'active',Priority:'high',Start_Date:ts(0,15),Due_Date:ts(11,15),Progress:45,Next_Action:'Préparer le prochain comité de pilotage',Risks:'Clarifier la gouvernance et le calendrier',Decision:'Valider les priorités du prochain trimestre',Review:true},{id:2,Name:'TNE — Territoire numérique éducatif',Type:'Programme pluriannuel',Status:'active',Priority:'medium',Start_Date:ts(0,1),Due_Date:ts(11,31),Progress:65,Next_Action:'Consolider le bilan intermédiaire',Risks:'Données de plusieurs partenaires à réunir',Decision:'',Review:true}];state.tasks=[{id:1,Title:'Préparer la visio AMVE',Project_Id:1,Type:'micro',Status:'todo',Priority:'high',Due_Date:ts(new Date().getMonth(),new Date().getDate()+2),Estimated_Hours:1.5,Notes:'Préparer l’ordre du jour'},{id:2,Title:'Mettre à jour le bilan TNE',Project_Id:2,Type:'task',Status:'progress',Priority:'medium',Start_Date:ts(3,1),Due_Date:ts(8,30),Estimated_Hours:8,Notes:''},{id:3,Title:'Envoyer le compte rendu',Project_Id:null,Type:'micro',Status:'waiting',Priority:'low',Due_Date:ts(new Date().getMonth(),new Date().getDate()-1),Estimated_Hours:.5,Notes:'Attente de validation'}];state.time=[];demoSave()}
function demoSave(){localStorage.setItem('pm-solo-demo',JSON.stringify({projects:state.projects,tasks:state.tasks,time:state.time}))}
function nextId(a){return a.reduce(function(m,x){return Math.max(m,Number(x.id)||0)},0)+1}

async function loadData(){if(state.demo){demoLoad()}else{var all=await Promise.all([grist.docApi.fetchTable(TABLES.projects),grist.docApi.fetchTable(TABLES.tasks),grist.docApi.fetchTable(TABLES.time)]);state.projects=records(all[0],projectMap());state.tasks=records(all[1],taskMap());state.time=records(all[2],timeMap())}refresh()}
async function addRecord(table,fields){if(state.demo){var list=table===TABLES.projects?state.projects:table===TABLES.tasks?state.tasks:state.time;var rec=Object.assign({id:nextId(list)},fields);list.push(rec);demoSave();return rec.id}var r=await grist.docApi.applyUserActions([['AddRecord',table,null,fields]]);return r&&r.retValues?r.retValues[0]:r}
async function updateRecord(table,id,fields){if(state.demo){var list=table===TABLES.projects?state.projects:table===TABLES.tasks?state.tasks:state.time;var rec=list.find(function(x){return String(x.id)===String(id)});Object.assign(rec,fields);demoSave()}else await grist.docApi.applyUserActions([['UpdateRecord',table,Number(id),fields]])}
async function removeRecord(table,id){if(state.demo){var key=table===TABLES.projects?'projects':table===TABLES.tasks?'tasks':'time';state[key]=state[key].filter(function(x){return String(x.id)!==String(id)});demoSave()}else await grist.docApi.applyUserActions([['RemoveRecord',table,Number(id)]])}

function normKey(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function sourceColumn(data,candidates){var keys=Object.keys(data||{}),wanted=candidates.map(normKey);for(var i=0;i<keys.length;i++){var n=normKey(keys[i]);if(wanted.indexOf(n)!==-1)return keys[i]}for(var j=0;j<keys.length;j++){var nk=normKey(keys[j]);if(wanted.some(function(w){return nk.indexOf(w)!==-1||w.indexOf(nk)!==-1}))return keys[j]}return null}
function importedStatus(v){var n=normKey(v);if(n.indexOf('final')!==-1||n.indexOf('termine')!==-1)return'done';if(n.indexOf('annul')!==-1||n.indexOf('horsimc')!==-1)return'cancelled';if(n.indexOf('encours')!==-1)return'active';if(n.indexOf('attente')!==-1||n.indexOf('arbitrage')!==-1)return'waiting';return'planned'}
function importedPriority(v){var n=normKey(v);return n.indexOf('haute')!==-1?'high':n.indexOf('basse')!==-1?'low':'medium'}
function cleanImportedDate(v){if(!v)return null;var d=day(v);if(!d&&typeof v==='string')d=new Date(v);if(!d||isNaN(d)||d.getFullYear()>2100||d.getFullYear()<2000)return null;return typeof v==='number'?v:Math.floor(d.getTime()/1000)}
function importedDuplicateIds(){var seen={};return state.projects.filter(function(p){if(p.Source_Table!=='Projet_innovants'||!p.Source_Record_Id)return false;var key=String(p.Source_Record_Id);if(seen[key])return true;seen[key]=true;return false}).map(function(p){return p.id})}
async function importExistingProjects(){
  if(state.demo){toast('L’import fonctionne uniquement dans votre document Grist');return}
  if(state.importing)return;
  var duplicates=importedDuplicateIds();
  if(duplicates.length){
    if(!confirm('Supprimer '+duplicates.length+' doublon(s) créé(s) lors de l’import précédent ?'))return;
    state.importing=true;updateImportButton();
    try{for(var d=0;d<duplicates.length;d++)await removeRecord(TABLES.projects,duplicates[d]);await loadData();toast(duplicates.length+' doublon(s) supprimé(s).')}finally{state.importing=false;updateImportButton()}
    return;
  }
  state.importing=true;updateImportButton();
  try{
    var data;try{data=await grist.docApi.fetchTable('Projet_innovants')}catch(e){toast('Table « Projet_innovants » introuvable. Nous ajusterons son identifiant dans Grist.');return}
    var cols={name:sourceColumn(data,['Nom_de_projet_Innovant','Nom de projet Innovant','AFF_Nom_du_projet_Innovant']),status:sourceColumn(data,['Statut']),priority:sourceColumn(data,['Importance']),due:sourceColumn(data,['date_de_fin_detape_Innovation','date de fin étape Innovation']),notes:sourceColumn(data,['notes_etapes_en_cours','notes étapes en cours']),type:sourceColumn(data,['Etape_de_la_boucle','Etape de la boucle']),risks:sourceColumn(data,['Points_de_vigilance','Points de vigilance'])};
    if(!cols.name){toast('Colonne du nom de projet introuvable');return}
    var existing={};state.projects.forEach(function(p){if(p.Source_Table==='Projet_innovants'&&p.Source_Record_Id)existing[p.Source_Record_Id]=true});
    var count=0;
    for(var i=0;i<data.id.length;i++){
      if(existing[data.id[i]])continue;
      var name=data[cols.name]&&data[cols.name][i];if(!name)continue;
      existing[data.id[i]]=true;
      await addRecord(TABLES.projects,{Name:String(name).trim(),Type:cols.type&&data[cols.type]?String(data[cols.type][i]||''): '',Status:importedStatus(cols.status&&data[cols.status]?data[cols.status][i]:''),Priority:importedPriority(cols.priority&&data[cols.priority]?data[cols.priority][i]:''),Start_Date:null,Due_Date:cleanImportedDate(cols.due&&data[cols.due]?data[cols.due][i]:null),Progress:0,Next_Action:cols.notes&&data[cols.notes]?String(data[cols.notes][i]||''):'',Risks:cols.risks&&data[cols.risks]?String(data[cols.risks][i]||''):'',Decision:'',Review:false,Source_Table:'Projet_innovants',Source_Record_Id:data.id[i],Created_At:now(),Updated_At:now()});count++;
    }
    await loadData();toast(count?count+' projet(s) importé(s).':'Aucun nouveau projet à importer.');
  }finally{state.importing=false;updateImportButton()}
}
function updateImportButton(){var b=$('import-projects');if(!b)return;var duplicates=importedDuplicateIds().length;b.disabled=state.importing;b.textContent=state.importing?'Import en cours…':duplicates?'Nettoyer '+duplicates+' doublon(s)':'Importer Projet_innovants'}

function filteredTasks(){return state.tasks.filter(function(t){if(state.project&&String(t.Project_Id)!==String(state.project))return false;if(!state.showDone&&isDone(t.Status))return false;return true})}
function timeForTask(id,year){return state.time.filter(function(x){return String(x.Task_Id)===String(id)&&x.End_Time&&(!year||new Date(x.End_Time*1000).getFullYear()===year)}).reduce(function(s,x){return s+(Number(x.Duration)||0)},0)}
function timeForProject(id,year){return state.tasks.filter(function(t){return String(t.Project_Id)===String(id)}).reduce(function(s,t){return s+timeForTask(t.id,year)},0)}
function activeEntry(){return state.time.find(function(x){return !x.End_Time})}

function refreshSelectors(){var p=$('project-filter'),v=p.value;p.innerHTML='<option value="">Tous les projets</option>'+state.projects.slice().sort(function(a,b){return a.Name.localeCompare(b.Name)}).map(function(x){return '<option value="'+x.id+'">'+esc(x.Name)+'</option>'}).join('');p.value=state.project||v||'';var tp=$('task-project'),tv=tp.value;tp.innerHTML='<option value="">Sans projet</option>'+state.projects.map(function(x){return '<option value="'+x.id+'">'+esc(x.Name)+'</option>'}).join('');tp.value=tv;var yf=$('year-filter');if(!yf.options.length){var y=new Date().getFullYear(),html='';for(var i=y-3;i<=y+2;i++)html+='<option value="'+i+'">'+i+'</option>';yf.innerHTML=html;yf.value=state.year}}
function refresh(){refreshSelectors();updateImportButton();renderDashboard();renderKanban();renderCalendar();renderGantt();renderReview();renderRunning()}

function renderDashboard(){var y=state.year,tasks=state.tasks.filter(function(t){return !state.project||String(t.Project_Id)===String(state.project)}),doneY=tasks.filter(function(t){return t.Completed_At&&new Date(t.Completed_At*1000).getFullYear()===y}),active=tasks.filter(function(t){return !isDone(t.Status)}),over=active.filter(function(t){var d=day(t.Due_Date);return d&&d<new Date(new Date().setHours(0,0,0,0))}),sec=tasks.reduce(function(s,t){return s+timeForTask(t.id,y)},0),projects=state.projects.filter(function(p){return !isDone(p.Status)});$('metrics').innerHTML=metric('Projets actifs',projects.length,'En cours ou à préparer')+metric('Tâches ouvertes',active.length,'Tous projets confondus')+metric('Terminées en '+y,doneY.length,'Trace de l’activité')+metric('En retard',over.length,'À replanifier ou terminer')+metric('Temps suivi',duration(sec),'Chronométré ou saisi');var soon=active.filter(function(t){var d=day(t.Due_Date);if(!d)return false;var diff=(d-new Date().setHours(0,0,0,0))/864e5;return diff<=14}).sort(function(a,b){return (a.Due_Date||9e15)-(b.Due_Date||9e15)}).slice(0,12);$('attention-list').innerHTML=soon.length?'<div class="list">'+soon.map(function(t){var overdue=day(t.Due_Date)<new Date(new Date().setHours(0,0,0,0));return '<div class="list-row"><div><div class="list-title">'+esc(t.Title)+'</div><div class="sub">'+esc(projectName(t.Project_Id))+'</div></div><span>'+fmtDate(t.Due_Date)+'</span>'+badge(t.Priority,'priority')+'<button class="btn small" onclick="openTask('+t.id+')">Ouvrir</button></div>'}).join('')+'</div>':'<div class="empty">Aucune échéance proche.</div>';var standalone=doneY.filter(function(t){return !t.Project_Id}).length;var exact=tasks.filter(function(t){return timeForTask(t.id,y)>0}).length;$('activity-summary').innerHTML='<div class="list"><div class="list-row"><div class="list-title">Tâches autonomes terminées</div><strong>'+standalone+'</strong></div><div class="list-row"><div class="list-title">Tâches avec temps suivi</div><strong>'+exact+'</strong></div><div class="list-row"><div class="list-title">Projets présentés en revue</div><strong>'+state.projects.filter(function(p){return p.Review}).length+'</strong></div></div>'}
function metric(label,value,small){return '<div class="metric"><span>'+label+'</span><strong>'+value+'</strong><small>'+small+'</small></div>'}

function renderKanban(){var ts=filteredTasks(),html='';TASK_STATUSES.filter(function(s){return state.showDone||!isDone(s[0])}).forEach(function(s){var list=ts.filter(function(t){return t.Status===s[0]});html+='<div class="lane" data-status="'+s[0]+'"><div class="lane-head"><span>'+s[1]+'</span><span class="badge">'+list.length+'</span></div><div class="lane-list">'+list.map(taskCard).join('')+'</div></div>'});$('kanban').innerHTML=html;document.querySelectorAll('.task-card').forEach(function(c){c.draggable=true;c.addEventListener('dragstart',function(){c.classList.add('dragging')});c.addEventListener('dragend',function(){c.classList.remove('dragging')})});document.querySelectorAll('.lane').forEach(function(l){l.addEventListener('dragover',function(e){e.preventDefault()});l.addEventListener('drop',async function(e){e.preventDefault();var c=document.querySelector('.task-card.dragging');if(!c)return;var t=state.tasks.find(function(x){return String(x.id)===c.dataset.id});var st=l.dataset.status,fields={Status:st,Updated_At:now()};if(st==='done'&&!t.Completed_At)fields.Completed_At=now();if(st!=='done')fields.Completed_At=null;await updateRecord(TABLES.tasks,t.id,fields);await loadData()})})}
function taskCard(t){var d=day(t.Due_Date),over=d&&d<new Date(new Date().setHours(0,0,0,0))&&!isDone(t.Status),tm=timeForTask(t.id);return '<article class="task-card '+(over?'overdue':'')+'" data-id="'+t.id+'" onclick="openTask('+t.id+')"><div>'+badge(t.Priority,'priority')+'</div><h4>'+esc(t.Title)+'</h4><div class="sub">'+esc(projectName(t.Project_Id))+'</div><div class="card-meta">'+(t.Due_Date?'<span class="badge '+(over?'red':'')+'">'+fmtDate(t.Due_Date)+'</span>':'')+(tm?'<span class="badge blue">'+duration(tm)+'</span>':'')+'</div></article>'}

function renderCalendar(){var base=state.calendar,y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));$('cal-title').textContent=MONTHS[m]+' '+y;var html=['lun','mar','mer','jeu','ven','sam','dim'].map(function(x){return '<div class="cal-dow">'+x.toUpperCase()+'</div>'}).join('');for(var i=0;i<42;i++){var d=new Date(start);d.setDate(start.getDate()+i);var key=localDateKey(d),events=[];state.tasks.forEach(function(t){if(dateValue(t.Due_Date)===key&&(!state.project||String(t.Project_Id)===String(state.project))&&(state.showDone||!isDone(t.Status)))events.push('<span class="event '+(d<new Date().setHours(0,0,0,0)&&!isDone(t.Status)?'over':'')+'" onclick="openTask('+t.id+')">'+esc(t.Title)+'</span>')});state.projects.forEach(function(p){if(dateValue(p.Due_Date)===key&&(!state.project||String(p.id)===String(state.project))&&(state.showDone||!isDone(p.Status)))events.push('<span class="event project" onclick="openProject('+p.id+')">◆ '+esc(p.Name)+'</span>')});html+='<div class="cal-day '+(d.getMonth()!==m?'out':'')+'"><span class="cal-num">'+d.getDate()+'</span>'+events.join('')+'</div>'}$('calendar').innerHTML=html}

function renderGantt(){var y=state.year,start=new Date(y,0,1),end=new Date(y+1,0,1),span=end-start,ps=state.projects.filter(function(p){return (!state.project||String(p.id)===String(state.project))&&(state.showDone||!isDone(p.Status))});var months='<div class="gantt-row"><div class="gantt-name"><strong>Éléments</strong></div><div class="gantt-months">'+MONTHS.map(function(x){return '<span>'+x.slice(0,3)+'</span>'}).join('')+'</div></div>',rows='';ps.forEach(function(p){rows+=ganttRow(p.Name,p.Start_Date,p.Due_Date,start,span,false,p.id);state.tasks.filter(function(t){return String(t.Project_Id)===String(p.id)&&(state.showDone||!isDone(t.Status))}).forEach(function(t){rows+=ganttRow(t.Title,t.Start_Date||t.Due_Date,t.Due_Date||t.Start_Date,start,span,true,t.id)})});var orphan=state.tasks.filter(function(t){return !t.Project_Id&&(state.showDone||!isDone(t.Status))});orphan.forEach(function(t){rows+=ganttRow(t.Title,t.Start_Date||t.Due_Date,t.Due_Date||t.Start_Date,start,span,true,t.id)});$('gantt').innerHTML='<div class="gantt">'+months+(rows||'<div class="empty">Ajoutez des dates de début et de fin pour afficher le Gantt.</div>')+'</div>'}
function ganttRow(name,a,b,start,span,task,id){var da=day(a),db=day(b),bar='';if(da||db){da=da||db;db=db||da;var left=Math.max(0,Math.min(100,(da-start)/span*100)),right=Math.max(0,Math.min(100,(db-start)/span*100)),width=Math.max(.5,right-left+.3);bar='<span class="gantt-bar" style="left:'+left+'%;width:'+width+'%">'+esc(name)+'</span>'}return '<div class="gantt-row '+(task?'task':'')+'"><div class="gantt-name" onclick="'+(task?'openTask':'openProject')+'('+id+')">'+esc(name)+'</div><div class="gantt-track">'+bar+'</div></div>'}

function renderReview(){var ps=state.projects.filter(function(p){return p.Review&&(!state.project||String(p.id)===String(state.project))});$('review').innerHTML=ps.length?ps.map(function(p){var open=state.tasks.filter(function(t){return String(t.Project_Id)===String(p.id)&&!isDone(t.Status)}).length,sec=timeForProject(p.id,state.year);return '<article class="project-card"><div>'+badge(p.Status)+' '+badge(p.Priority,'priority')+'</div><h3>'+esc(p.Name)+'</h3><div class="sub">'+esc(p.Type||'Projet')+' · '+fmtDate(p.Start_Date)+' → '+fmtDate(p.Due_Date)+'</div><div class="progress"><i style="width:'+Math.max(0,Math.min(100,p.Progress||0))+'%"></i></div><div class="sub">Avancement : '+(p.Progress||0)+' % · '+open+' tâche(s) ouverte(s)</div>'+reviewBlock('Prochaine action',p.Next_Action)+reviewBlock('Points de vigilance',p.Risks)+reviewBlock('Décision attendue',p.Decision)+'<div class="review-footer"><span>'+duration(sec)+' suivies en '+state.year+'</span><button class="btn small" onclick="openProject('+p.id+')">Modifier</button></div></article>'}).join(''):'<div class="empty">Cochez « Afficher dans la revue » sur les projets à présenter.</div>'}
function reviewBlock(label,text){return text?'<div class="review-block"><b>'+label+'</b><p>'+esc(text)+'</p></div>':''}

function renderRunning(){var e=activeEntry(),el=$('running-summary');if(!e){el.classList.add('hidden');return}var t=state.tasks.find(function(x){return String(x.id)===String(e.Task_Id)});el.classList.remove('hidden');el.textContent='Chronomètre : '+(t?t.Title:'Tâche')+' · '+duration(now()-e.Start_Time);if(!$('task-modal').classList.contains('hidden')&&String($('task-id').value)===String(e.Task_Id))renderTimer(e.Task_Id)}
function renderTimer(taskId){var e=activeEntry(),running=e&&String(e.Task_Id)===String(taskId),total=timeForTask(taskId)+(running?now()-e.Start_Time:0);$('timer-clock').textContent=duration(total);$('timer-toggle').textContent=running?'Arrêter':'Démarrer';$('timer-toggle').className='btn '+(running?'danger':'primary');$('time-list').innerHTML=state.time.filter(function(x){return String(x.Task_Id)===String(taskId)&&x.End_Time}).sort(function(a,b){return b.Start_Time-a.Start_Time}).slice(0,10).map(function(x){return '<div class="time-row"><span>'+new Date(x.Start_Time*1000).toLocaleDateString('fr-FR')+' · '+esc(x.Description||x.Source||'Session')+'</span><strong>'+duration(x.Duration)+'</strong></div>'}).join('')}

function showModal(id){$(id).classList.remove('hidden')}function closeModal(id){$(id).classList.add('hidden')}
function openTask(id,quick){var t=state.tasks.find(function(x){return String(x.id)===String(id)});$('task-form').reset();$('task-id').value=t?t.id:'';$('task-modal-title').textContent=t?'Modifier la tâche':quick?'Tâche rapide':'Nouvelle tâche';$('task-title').value=t?t.Title:'';$('task-project').value=t&&t.Project_Id?t.Project_Id:state.project||'';$('task-type').value=t?t.Type||'task':quick?'micro':'task';$('task-status').value=t?t.Status||'todo':'todo';$('task-priority').value=t?t.Priority||'medium':'medium';$('task-start').value=t?dateValue(t.Start_Date):'';$('task-due').value=t?dateValue(t.Due_Date):'';$('task-estimate').value=t&&t.Estimated_Hours!=null?t.Estimated_Hours:'';$('task-review').checked=!!(t&&t.Review);$('task-notes').value=t?t.Notes||'':'';$('delete-task').classList.toggle('hidden',!t);$('timer-box').classList.toggle('hidden',!t);showModal('task-modal');if(t)renderTimer(t.id);setTimeout(function(){$('task-title').focus()},10)}
function openProject(id){var p=state.projects.find(function(x){return String(x.id)===String(id)});$('project-form').reset();$('project-id').value=p?p.id:'';$('project-modal-title').textContent=p?'Modifier le projet':'Nouveau projet';$('project-name').value=p?p.Name:'';$('project-type').value=p?p.Type||'':'';$('project-status').value=p?p.Status||'active':'active';$('project-priority').value=p?p.Priority||'medium':'medium';$('project-progress').value=p?p.Progress||0:0;$('project-start').value=p?dateValue(p.Start_Date):'';$('project-due').value=p?dateValue(p.Due_Date):'';$('project-next').value=p?p.Next_Action||'':'';$('project-risks').value=p?p.Risks||'':'';$('project-decision').value=p?p.Decision||'':'';$('project-review').checked=!!(p&&p.Review);$('delete-project').classList.toggle('hidden',!p);showModal('project-modal');setTimeout(function(){$('project-name').focus()},10)}
window.openTask=openTask;window.openProject=openProject;

async function saveTask(e){e.preventDefault();var id=$('task-id').value,st=$('task-status').value,old=state.tasks.find(function(x){return String(x.id)===String(id)}),fields={Title:$('task-title').value.trim(),Project_Id:$('task-project').value?Number($('task-project').value):null,Type:$('task-type').value,Status:st,Priority:$('task-priority').value,Start_Date:unix($('task-start').value),Due_Date:unix($('task-due').value),Notes:$('task-notes').value.trim(),Estimated_Hours:$('task-estimate').value===''?null:Number($('task-estimate').value),Review:$('task-review').checked,Updated_At:now()};if(!fields.Title)return;if(st==='done'&&(!old||!old.Completed_At))fields.Completed_At=now();else if(st!=='done')fields.Completed_At=null;if(id)await updateRecord(TABLES.tasks,id,fields);else{fields.Created_At=now();await addRecord(TABLES.tasks,fields)}closeModal('task-modal');await loadData();toast('Tâche enregistrée')}
async function saveProject(e){e.preventDefault();var id=$('project-id').value,fields={Name:$('project-name').value.trim(),Type:$('project-type').value.trim(),Status:$('project-status').value,Priority:$('project-priority').value,Progress:Number($('project-progress').value)||0,Start_Date:unix($('project-start').value),Due_Date:unix($('project-due').value),Next_Action:$('project-next').value.trim(),Risks:$('project-risks').value.trim(),Decision:$('project-decision').value.trim(),Review:$('project-review').checked,Updated_At:now()};if(!fields.Name)return;if(id)await updateRecord(TABLES.projects,id,fields);else{fields.Created_At=now();await addRecord(TABLES.projects,fields)}closeModal('project-modal');await loadData();toast('Projet enregistré')}
async function toggleTimer(){var taskId=Number($('task-id').value),e=activeEntry();if(e){if(String(e.Task_Id)!==String(taskId)){toast('Arrêtez d’abord le chronomètre déjà actif');return}var end=now();await updateRecord(TABLES.time,e.id,{End_Time:end,Duration:end-e.Start_Time});toast('Temps enregistré : '+duration(end-e.Start_Time))}else await addRecord(TABLES.time,{Task_Id:taskId,Start_Time:now(),End_Time:null,Duration:0,Description:'',Source:'timer',Created_At:now()});await loadData();renderTimer(taskId)}
async function manualTime(){var taskId=Number($('task-id').value),h=Number($('manual-hours').value)||0,m=Number($('manual-minutes').value)||0,sec=Math.round((h*60+m)*60);if(sec<=0){toast('Indiquez une durée');return}var end=now();await addRecord(TABLES.time,{Task_Id:taskId,Start_Time:end-sec,End_Time:end,Duration:sec,Description:'Saisie manuelle',Source:'manual',Created_At:end});$('manual-hours').value='';$('manual-minutes').value='';await loadData();renderTimer(taskId);toast('Temps ajouté')}

function bind(){document.querySelectorAll('.tab').forEach(function(b){b.addEventListener('click',function(){state.view=b.dataset.view;document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.view').forEach(function(x){x.classList.toggle('active',x.id==='view-'+state.view)})})});document.querySelectorAll('[data-close]').forEach(function(b){b.addEventListener('click',function(){closeModal(b.dataset.close)})});$('quick-task').onclick=function(){openTask(null,true)};$('new-project').onclick=function(){openProject()};$('import-projects').onclick=importExistingProjects;$('task-form').onsubmit=saveTask;$('project-form').onsubmit=saveProject;$('timer-toggle').onclick=toggleTimer;$('add-time').onclick=manualTime;$('project-filter').onchange=function(){state.project=this.value;refresh()};$('year-filter').onchange=function(){state.year=Number(this.value);refresh()};$('show-done').onchange=function(){state.showDone=this.checked;refresh()};$('cal-prev').onclick=function(){state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()-1,1);renderCalendar()};$('cal-next').onclick=function(){state.calendar=new Date(state.calendar.getFullYear(),state.calendar.getMonth()+1,1);renderCalendar()};$('cal-today').onclick=function(){state.calendar=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCalendar()};$('delete-task').onclick=async function(){var id=$('task-id').value;if(!id||!confirm('Supprimer cette tâche et ses entrées de temps ?'))return;var entries=state.time.filter(function(x){return String(x.Task_Id)===String(id)});for(var i=0;i<entries.length;i++)await removeRecord(TABLES.time,entries[i].id);await removeRecord(TABLES.tasks,id);closeModal('task-modal');await loadData()};$('delete-project').onclick=async function(){var id=$('project-id').value;if(!id)return;var count=state.tasks.filter(function(x){return String(x.Project_Id)===String(id)}).length;if(!confirm('Supprimer ce projet ? Ses '+count+' tâche(s) deviendront autonomes.'))return;for(var i=0;i<state.tasks.length;i++)if(String(state.tasks[i].Project_Id)===String(id))await updateRecord(TABLES.tasks,state.tasks[i].id,{Project_Id:null});await removeRecord(TABLES.projects,id);closeModal('project-modal');await loadData()};document.querySelectorAll('.modal-bg').forEach(function(m){m.addEventListener('click',function(e){if(e.target===m)closeModal(m.id)})})}

async function init(){bind();$('task-status').innerHTML=TASK_STATUSES.map(function(s){return '<option value="'+s[0]+'">'+s[1]+'</option>'}).join('');state.demo=!(window.grist&&window.parent!==window);if(state.demo){$('demo-banner').classList.remove('hidden');demoLoad();refresh()}else{try{await grist.ready({requiredAccess:'full'});await ensureTables();await loadData();grist.onRecords(function(){loadData().catch(console.error)})}catch(e){console.error(e);toast('Connexion à Grist impossible : '+e.message)}}state.tick=setInterval(renderRunning,1000)}
init();
